<?php
// =============================================================================
// idp/metadata/saml20-idp-hosted.php — SAML 2.0 IdP hosted metadata
//
// Defines THIS IdP's SAML 2.0 entity: signing certificate, auth source,
// NameID policy, and the authproc attribute processing pipeline.
//
// SIGNING CERTIFICATE
// ────────────────────
// The IdP signs SAML assertions with a dedicated self-signed RSA-3072 cert
// generated by init.sh at first boot and persisted in the `idp-cert` volume.
// This cert is INTENTIONALLY separate from the Vault PKI trust hierarchy:
//   • Vault PKI is for mTLS / x509 client auth (device identity layer)
//   • SAML signing cert is for assertion integrity (IdP identity layer)
// A compromise of the SAML signing key lets an attacker forge SAML assertions
// but NOT issue mTLS certs — the blast radius is bounded.
//
// ATTRIBUTE PIPELINE (authproc)
// ──────────────────────────────
// Step 10 — uid format guard:  reject logins with malformed uids before any
//            attribute processing, preventing downstream injection.
// Step 20 — NameID from uid:   sets the SAML NameID to the uid value.
// Step 30 — OID rename:        maps LDAP attribute names to SAML OID URNs
//            (required for Shibboleth SP attribute mapping by OID).
// Step 40 — Attribute limit:   whitelist of attributes to release.  All other
//            attributes (including userCertificate;binary, userPassword if it
//            somehow appeared) are stripped here.
// Step 90 — Audit log:         (reserved for future authproc logging filter)
//
// SAML ATTRIBUTE NAMES RELEASED
// ───────────────────────────────
// Friendly name          OID URN                                  Source in LDAP
// ─────────────────────────────────────────────────────────────────────────────
// uid                    urn:oid:0.9.2342.19200300.100.1.1        uid
// mail                   urn:oid:0.9.2342.19200300.100.1.3        mail
// cn                     urn:oid:2.5.4.3                          cn
// givenName              urn:oid:2.5.4.42                         givenName
// sn                     urn:oid:2.5.4.4                          sn
// ssoCertThumbprint      urn:oid:1.3.6.1.4.1.99999.1.2           ssoCertThumbprint
// ssoDeviceFingerprint   urn:oid:1.3.6.1.4.1.99999.1.1           ssoDeviceFingerprint
// ssoEnrolledAt          urn:oid:1.3.6.1.4.1.99999.1.3           ssoEnrolledAt
// =============================================================================

declare(strict_types=1);

$idpEntityId = getenv('IDP_ENTITY_ID')
    ?: 'https://idp.sso.local/simplesaml/saml2/idp/metadata.php';

$metadata[$idpEntityId] = [

    // ── Identity ──────────────────────────────────────────────────────────────
    // host => __DEFAULT__ lets SSP resolve this entry for any incoming hostname.
    // Without this, SSP's host-based lookup fails even when there is only one entry.
    'host' => '__DEFAULT__',

    // Auth source key (must match a key in authsources.php).
    'auth' => 'sso-ldap',

    // ── Signing and encryption keys ───────────────────────────────────────────
    // These files are in /var/simplesamlphp/cert/ (persisted in the idp-cert volume).
    // Generated by init.sh at first boot using openssl req -newkey rsa:3072.
    'certificate' => 'idp.crt',
    'privatekey'  => 'idp.pem',

    // Signature algorithm for SAML responses and assertions.
    'signature.algorithm' => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',

    // Assertion encryption: disabled in dev (no SP encryption cert configured yet).
    // PROD: set to true and add the SP's encryption cert in saml20-sp-remote.php.
    'assertion.encryption' => false,

    // ── NameID policy ─────────────────────────────────────────────────────────
    // 'unspecified' lets the SP request any format; we default to persistent.
    // Step 20 in authproc overrides the NameID value from the uid attribute.
    'NameIDFormat' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',

    // ── Attribute name format ─────────────────────────────────────────────────
    // URI format matches standard SAML attribute OID names (required for
    // Shibboleth SP attribute-resolver.xml to map by OID).
    'attributes.NameFormat' => 'urn:oasis:names:tc:SAML:2.0:attrname-format:uri',

    // ── authproc filter chain ─────────────────────────────────────────────────
    'authproc' => [

        // ── Step 10: uid format guard ─────────────────────────────────────────
        // Reject assertions for users whose uid doesn't match our strict format.
        // This matches provision_user_role()'s regex and blocks injection attempts
        // before any downstream processing.
        10 => [
            'class' => 'core:PHP',
            'code'  => '
                if (!isset($attributes["uid"][0])) {
                    throw new \SimpleSAML\Error\Exception("No uid attribute returned from LDAP.");
                }
                $uid = $attributes["uid"][0];
                if (!preg_match(\'/^[a-z][a-z0-9_-]{0,62}$/\', $uid)) {
                    throw new \SimpleSAML\Error\Exception(
                        "Rejected login: uid \'$uid\' fails format validation."
                    );
                }
            ',
        ],

        // ── Step 20: set SAML NameID from uid attribute ───────────────────────
        // The NameID is the persistent identifier used by the SP to identify the
        // user across sessions. We use the LDAP uid (e.g., "alice") which also
        // equals the PostgreSQL role name and the x509 cert CN.
        20 => [
            'class'               => 'saml:AttributeNameID',
            'identifyingAttribute' => 'uid',
            'Format'              => 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
        ],

        // ── Step 30: rename LDAP attributes to SAML OID URN names ────────────
        // SSP receives attributes with LDAP names; the Shibboleth SP expects
        // urn:oid: URNs in the assertion.  This filter renames them in place.
        // Custom attributes use our private OID arc (1.3.6.1.4.1.99999.*).
        30 => [
            'class'  => 'core:AttributeMap',
            // LDAP name → SAML urn:oid: name
            'uid'                  => 'urn:oid:0.9.2342.19200300.100.1.1',
            'mail'                 => 'urn:oid:0.9.2342.19200300.100.1.3',
            'cn'                   => 'urn:oid:2.5.4.3',
            'givenName'            => 'urn:oid:2.5.4.42',
            'sn'                   => 'urn:oid:2.5.4.4',
            'ssoCertThumbprint'    => 'urn:oid:1.3.6.1.4.1.99999.1.2',
            'ssoDeviceFingerprint' => 'urn:oid:1.3.6.1.4.1.99999.1.1',
            'ssoEnrolledAt'        => 'urn:oid:1.3.6.1.4.1.99999.1.3',
        ],

        // ── Step 40: attribute whitelist ─────────────────────────────────────
        // Only these OID-named attributes are released in the assertion.
        // Everything else (including userCertificate;binary, objectClass,
        // userPassword if it somehow appeared) is silently stripped.
        40 => [
            'class' => 'core:AttributeLimit',
            'default' => false,   // strip anything not listed below
            // Standard identity attributes
            'urn:oid:0.9.2342.19200300.100.1.1',  // uid
            'urn:oid:0.9.2342.19200300.100.1.3',  // mail
            'urn:oid:2.5.4.3',                    // cn
            'urn:oid:2.5.4.42',                   // givenName
            'urn:oid:2.5.4.4',                    // sn
            // SSO-specific attributes (needed by the Golang app for cert binding)
            'urn:oid:1.3.6.1.4.1.99999.1.2',     // ssoCertThumbprint
            'urn:oid:1.3.6.1.4.1.99999.1.1',     // ssoDeviceFingerprint
            'urn:oid:1.3.6.1.4.1.99999.1.3',     // ssoEnrolledAt
        ],

    ], // end authproc

    // ── Single logout ─────────────────────────────────────────────────────────
    // Disabled for the initial deployment; enable in prod once the SP supports it.
    // Do not set to an empty array — SSP validates endpoint Location strings and
    // will throw if the key exists but contains no valid endpoint entries.
    // 'SingleLogoutService' => [],

];
