-- =============================================================================
-- postgres/init/03-dev-seed.sql
-- Development seed data only.
--
-- Provisions the same development users defined in ldap/bootstrap/02-sample-users.ldif
-- (alice, bob) so the dev stack works end-to-end without running the full SAML
-- enrolment flow first.
--
-- In production: this file should not be present in the image.  Control via
-- a Dockerfile build arg (ARG INCLUDE_DEV_SEED=false) or by not mounting it.
--
-- All operations are idempotent (ON CONFLICT DO NOTHING / IF NOT EXISTS).
-- =============================================================================

\connect sso

DO $$
BEGIN

-- ── Provision LDAP dev users ──────────────────────────────────────────────────
-- These CNs must match the usernames in ldap/bootstrap/02-sample-users.ldif.
-- The x509 certs generated by ldap/scripts/gen-sample-certs.sh will have the
-- same CNs, which pg_ident.conf maps to these role names.
PERFORM provision_user_role('alice');
PERFORM provision_user_role('bob');

-- ── Seed placeholder enrolled certs ──────────────────────────────────────────
-- Thumbprints will be overwritten by consul-template when vault-agent renders
-- real certs and pushes them via ldap-cert-push.sh.  These placeholders allow
-- the schema FK constraint on sessions(thumbprint) to be satisfied during dev.
INSERT INTO enrolled_certs (
    username, serial, thumbprint, public_cert_pem, device_fp,
    issued_at, expires_at
) VALUES
    (
        'alice',
        'de:ad:00:00:00:00:00:01',
        'dev-placeholder-alice-thumb-AAAAAAAAAAAAAAAAAAAAAAAAA',
        '-----BEGIN CERTIFICATE-----' || chr(10) || 'PLACEHOLDER-ALICE' || chr(10) || '-----END CERTIFICATE-----',
        'dev-fp-alice-0000',
        now(),
        now() + interval '4 hours'
    ),
    (
        'bob',
        'de:ad:00:00:00:00:00:02',
        'dev-placeholder-bob-thumb-BBBBBBBBBBBBBBBBBBBBBBBBB',
        '-----BEGIN CERTIFICATE-----' || chr(10) || 'PLACEHOLDER-BOB' || chr(10) || '-----END CERTIFICATE-----',
        'dev-fp-bob-0000',
        now(),
        now() + interval '4 hours'
    )
ON CONFLICT (serial) DO NOTHING;

-- ── Seed audit event ─────────────────────────────────────────────────────────
INSERT INTO auth_events (event_type, username, details)
VALUES
    ('bootstrap', 'alice', '{"source": "03-dev-seed.sql", "note": "dev placeholder"}'),
    ('bootstrap', 'bob',   '{"source": "03-dev-seed.sql", "note": "dev placeholder"}')
;

RAISE NOTICE 'Dev seed complete: roles alice, bob provisioned.';
END $$;
