<?php
// =============================================================================
// idp/config/config.php — SimpleSAMLphp 2.x main configuration
//
// All secrets and hostnames are read via getenv() at runtime.
// No values are hardcoded here; the PHP process inherits the container's
// environment, which is set by docker-compose and init.sh.
//
// PRODUCTION CHECKLIST
// ─────────────────────
// □ SSP_SECRET_SALT — change to a 32+ char random string (make _gen-secrets sets this)
// □ SSP_ADMIN_PASSWORD — change to a strong password (in secrets/ssp_admin_password.txt)
// □ session.cookie.secure — set true (requires HTTPS)
// □ session.cookie.samesite — verify 'None' is correct for your SP setup
// □ admin.protectmetadata — set true once SP metadata is configured
// □ IDP_BASEURLPATH — must be the public HTTPS URL in production
// □ logging.handler — switch to 'syslog' or 'file' in production
// =============================================================================

declare(strict_types=1);

// ── Read admin password from Docker secret (init.sh sets SSP_ADMIN_PASSWORD) ─
$adminPassword = getenv('SSP_ADMIN_PASSWORD');
if ($adminPassword === false || $adminPassword === '') {
    // Fallback: read directly from the secret file if the env var wasn't set.
    // init.sh normally handles this before Apache starts.
    $secretFile = '/run/secrets/ssp_admin_password';
    $adminPassword = is_readable($secretFile) ? trim(file_get_contents($secretFile)) : 'CHANGE_ME';
}

$config = [

    // ── Core URLs ─────────────────────────────────────────────────────────────
    // baseurlpath: the public URL prefix for SimpleSAMLphp.
    // DEV:  http://idp.sso.local:8880/simplesaml/ (host port 8880 → container 80)
    // PROD: https://idp.sso.local/simplesaml/ (behind TLS terminator)
    'baseurlpath'  => getenv('IDP_BASEURLPATH') ?: 'https://idp.sso.local/simplesaml/',

    // ── Directory layout (standard SSP paths) ─────────────────────────────────
    'certdir'      => '/var/simplesamlphp/cert/',
    'loggingdir'   => '/var/log/apache2/',
    'datadir'      => '/var/simplesamlphp/data/',
    'tempdir'      => '/tmp/simplesamlphp',

    // ── Security ──────────────────────────────────────────────────────────────
    // secretsalt: random 32+ char string used for HMAC, cookie protection, etc.
    // Generated by `make _gen-secrets`; injected via docker-compose.
    'secretsalt'   => getenv('SSP_SECRET_SALT') ?: 'CHANGE_ME_RUN_MAKE_GEN_SECRETS',

    // Admin password for the /simplesaml/admin/ interface.
    // In SSP 2.x this may be a plain string or a bcrypt hash ($2y$...).
    // Set via Docker secret → init.sh → SSP_ADMIN_PASSWORD env var.
    'auth.adminpassword' => $adminPassword,

    // Restrict admin panel to authenticated admins.
    'admin.protectindexpage' => true,

    // Allow unauthenticated access to IdP metadata (SP needs to fetch it).
    // PROD: set to true and configure the SP to use a cached copy.
    'admin.protectmetadata' => false,

    // ── Enable IdP functionality ───────────────────────────────────────────────
    'enable.saml20-idp' => true,

    // ── Module enable ─────────────────────────────────────────────────────────
    // In SSP 2.x, modules that ship in the distribution must be explicitly enabled.
    'module.enable' => [
        'admin'    => true,
        'core'     => true,
        'saml'     => true,
        'ldap'     => true,   // LDAP auth source (authsources.php)
        'exampleauth' => false,
    ],

    // ── Logging ───────────────────────────────────────────────────────────────
    // DEV: stderr (visible in `docker compose logs idp`)
    // PROD: 'syslog' or 'file'
    'logging.level'   => 7,   // SimpleSAML\Logger::DEBUG = 7 (temporary)
    'logging.handler' => 'stderr',
    'logging.facility' => defined('LOG_USER') ? LOG_USER : 'user',
    'logging.processname' => 'simplesamlphp',
    'logging.logfile'  => 'simplesamlphp.log',

    // ── Session ───────────────────────────────────────────────────────────────
    'session.duration'                => 8 * 60 * 60,  // 8 hours max
    'session.datastore.timeout'       => 4 * 60 * 60,
    'session.state.timeout'           => 60,
    'session.cookie.name'             => 'SimpleSAMLphpSession',
    'session.cookie.lifetime'         => 0,
    'session.cookie.path'             => '/',
    'session.cookie.domain'           => '',
    'session.cookie.secure'           => false,    // PROD: true (requires HTTPS)
    'session.cookie.httponly'         => true,
    // Lax is correct for SAML: all IdP interactions are top-level navigations.
    // None requires Secure=true; IdP runs on plain HTTP in dev so use Lax.
    // PROD: switch to None + session.cookie.secure=true when IdP is behind HTTPS.
    'session.cookie.samesite'         => 'Lax',
    'session.phpsession.cookiename'   => 'SimpleSAML',
    'session.phpsession.savepath'     => null,     // use PHP default
    'session.phpsession.httponly'     => true,

    // ── Metadata ──────────────────────────────────────────────────────────────
    // SSP loads metadata from the metadata/ directory (flatfile format).
    'metadata.sources' => [
        ['type' => 'flatfile'],
    ],
    'metadata.sign.enable'    => false,
    'metadata.sign.algorithm' => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',

    // ── Store ─────────────────────────────────────────────────────────────────
    // phpsession is simplest for a single-node dev setup.
    // PROD: 'memcache' or 'redis' for multi-node.
    'store.type' => 'phpsession',

    // ── Crypto ────────────────────────────────────────────────────────────────
    // Signature algorithm used for SAML messages.
    'signature.algorithm' => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',

    // ── Language ──────────────────────────────────────────────────────────────
    'language.default'       => 'en',
    'language.available'     => ['en'],
    'language.rtl'           => [],

    // ── Contact ───────────────────────────────────────────────────────────────
    'technicalcontact_name'  => 'sso01a Admin',
    'technicalcontact_email' => 'admin@sso.local',

    // ── Timezone ──────────────────────────────────────────────────────────────
    'timezone' => 'UTC',

    // ── Proxy / trusted headers ───────────────────────────────────────────────
    // When running behind a reverse proxy (SP → IdP back-channel), trust these
    // headers for the public-facing URL.
    // PROD: set to the SP's IP range on the Docker internal network.
    'trusted.url.domains' => [],
    'trusted.url.regex'   => false,

    // ── Errors / debug ────────────────────────────────────────────────────────
    'debug' => [
        'saml'      => false,
        'backtraces' => true,
        'validatexml' => false,
    ],
    'showerrors'    => false,   // PROD: always false
    'errorreporting' => true,

];
