package db

import (
	"fmt"
	"regexp"
	"strings"
)

// reUnsafe matches any character that is not a lowercase ASCII letter, digit,
// or underscore — everything that must be collapsed to "_" in a PG role name.
var reUnsafe = regexp.MustCompile(`[^a-z0-9]+`)

// reValidRole is the strict allowlist for the final role name.
// PostgreSQL identifiers are up to 63 bytes; our prefix "u_" uses 2 of them.
var reValidRole = regexp.MustCompile(`^u_[a-z0-9_]{1,61}$`)

// roleForCN derives a safe PostgreSQL role name from a certificate Common Name.
//
// Transformation pipeline:
//  1. Lower-case the CN.
//  2. Collapse every run of non-[a-z0-9] characters to a single underscore.
//  3. Trim leading/trailing underscores.
//  4. Prepend "u_" to avoid collisions with built-in PG roles (postgres,
//     public, pg_*) and to make user roles visually distinct in pg_hba/logs.
//  5. Validate the result against the strict allowlist and 63-byte PG limit.
//
// Examples:
//
//	"jsmith"          → "u_jsmith"
//	"john.smith"      → "u_john_smith"
//	"John Smith"      → "u_john_smith"
//	"user@domain.org" → "u_user_domain_org"
//
// The CSRs generated by GenerateKeyAndCSR() use the raw LDAP uid as CN (no
// spaces, no @ signs in practice) so the transformation is usually a no-op
// beyond the "u_" prefix.  The sanitisation is defensive for edge cases.
func roleForCN(cn string) (string, error) {
	if cn == "" {
		return "", fmt.Errorf("certificate CN is empty")
	}

	safe := reUnsafe.ReplaceAllString(strings.ToLower(cn), "_")
	safe = strings.Trim(safe, "_")
	if safe == "" {
		return "", fmt.Errorf("CN %q produces an empty identifier after sanitisation", cn)
	}

	role := "u_" + safe
	if !reValidRole.MatchString(role) {
		// Catches: exceeds 63 bytes, or residual unexpected characters.
		return "", fmt.Errorf("derived role %q fails validation (check CN %q)", role, cn)
	}

	return role, nil
}

// RoleForCN is the exported variant for use outside the db package (e.g. in
// the enrolment handler to pre-create the PG role at cert issuance time).
func RoleForCN(cn string) (string, error) { return roleForCN(cn) }
