package db

import (
	"fmt"
	"regexp"
	"strings"
)

// reUnsafe matches any character that is not a lowercase ASCII letter, digit,
// or underscore — everything that must be collapsed to "_" in a PG role name.
var reUnsafe = regexp.MustCompile(`[^a-z0-9]+`)

// reValidRole is the strict allowlist for the final role name.
// Role names match the LDAP uid: lowercase alphanumeric, hyphens OK internally,
// 1–63 chars (PostgreSQL identifier limit).
var reValidRole = regexp.MustCompile(`^[a-z][a-z0-9_]{0,62}$`)

// reReserved guards against provisioning roles that collide with built-in or
// service accounts.  Vault PKI role's allowed_domains provides a first layer;
// this is belt-and-suspenders.
var reReserved = regexp.MustCompile(`^(postgres|sso_admin|sso_app|sso_auditor|public|pg_.*)$`)

// roleForCN derives a safe PostgreSQL role name from a certificate Common Name.
//
// Transformation pipeline:
//  1. Lower-case the CN.
//  2. Collapse every run of non-[a-z0-9] characters to a single underscore.
//  3. Trim leading/trailing underscores.
//  4. Validate the result against the strict allowlist and 63-byte PG limit.
//
// Examples:
//
//	"alice"      → "alice"
//	"john.smith" → "john_smith"
//
// The CSRs generated by GenerateKeyAndCSR() use the raw LDAP uid as CN (no
// spaces, no @ signs in practice) so the transformation is usually a no-op.
func roleForCN(cn string) (string, error) {
	if cn == "" {
		return "", fmt.Errorf("certificate CN is empty")
	}

	safe := reUnsafe.ReplaceAllString(strings.ToLower(cn), "_")
	safe = strings.Trim(safe, "_")
	if safe == "" {
		return "", fmt.Errorf("CN %q produces an empty identifier after sanitisation", cn)
	}

	if !reValidRole.MatchString(safe) {
		return "", fmt.Errorf("derived role %q fails validation (check CN %q)", safe, cn)
	}
	if reReserved.MatchString(safe) {
		return "", fmt.Errorf("CN %q maps to reserved role name %q", cn, safe)
	}

	return safe, nil
}

// RoleForCN is the exported variant for use outside the db package (e.g. in
// the enrolment handler to pre-create the PG role at cert issuance time).
func RoleForCN(cn string) (string, error) { return roleForCN(cn) }
